import React from 'react'


export const metadata = {
    title: "Employee list",
    description: "Generated by create next app",
};
export default function page() {
    return (
        <div>
            this is employee list
        </div>
    )
}
