import Header from "@/Components/Header/Header";
import "./globals.css";


export const metadata = {
  title: "Webbriks || HRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body>
        <div>
          <header>
            <Header/>
          </header>
          <main>
            {children}
          </main>
          <footer>

          </footer>
        </div>
      </body>
    </html>
  );
}
