import ReduxProvider from "@/redux/ReduxProvider";

import "./globals.css";
import AuthenticatedLayout from "./layouts/AuthenticatedLayout";
import UnauthenticatedLayout from "./layouts/UnauthenticatedLayout";

export const metadata = {
  title: "Webbriks || HRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isAuthenticated = false; // Replace with real authentication logic.

  return (
    <html lang="en" data-theme="light">
      <body>
        <ReduxProvider>
          {isAuthenticated ? (
            <AuthenticatedLayout>{children}</AuthenticatedLayout>
          ) : (
            <UnauthenticatedLayout>{children}</UnauthenticatedLayout>
          )}
        </ReduxProvider>
      </body>
    </html>
  );
}
